let data=null, profile=localStorage.getItem("profile")||"simon", selectedDay=new Date().getDay(); const names=["Sonntag","Montag","Dienstag","Mittwoch","Donnerstag","Freitag","Samstag"];
async function init(){data=await fetch("schedule.json").then(r=>r.json());render();setInterval(renderClock,1000);renderClock();if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js");}
function render(){document.body.classList.toggle("luisa",profile==="luisa");document.getElementById("title").textContent=data[profile].name;document.querySelectorAll(".profile").forEach(b=>b.classList.toggle("active",b.dataset.profile===profile));renderDays();renderLessons();renderClock();}
function renderDays(){const el=document.getElementById("days");el.innerHTML="";["Montag","Dienstag","Mittwoch","Donnerstag","Freitag"].forEach((d,i)=>{const b=document.createElement("button");b.className="day"+(selectedDay===i+1?" active":"");b.textContent=d.slice(0,2);b.onclick=()=>{selectedDay=i+1;render()};el.appendChild(b)})}
function renderLessons(){const day=names[selectedDay]||"Montag", lessons=data[profile].days[day]||[], el=document.getElementById("lessons");el.innerHTML=lessons.map((x,i)=>`<div class="lesson" data-i="${i}"><div class="time">${x[0]}<br>${x[1]}</div><div class="card"><div><div class="subject">${x[2]||"—"}</div><div class="room">${x[3]||""}</div></div><span class="badge">Stunde ${i+1}</span></div></div>`).join("");highlight();}
function mins(s){const [h,m]=s.split(":").map(Number);return h*60+m}
function highlight(){const now=new Date();if(now.getDay()!==selectedDay)return;const n=now.getHours()*60+now.getMinutes(), lessons=data[profile].days[names[selectedDay]]||[];let cur=-1;lessons.forEach((x,i)=>{if(n>=mins(x[0])&&n<mins(x[1]))cur=i});document.querySelectorAll(".lesson").forEach((e,i)=>e.classList.toggle("current",i===cur));document.getElementById("currentSubject").textContent=cur>=0?(lessons[cur][2]||"Pause"):"Keine aktuelle Stunde";}
function renderClock(){const now=new Date();document.getElementById("clock").textContent=now.toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"});document.getElementById("dateLabel").textContent=now.toLocaleDateString("de-DE",{weekday:"long",day:"2-digit",month:"long"});highlight();}
document.querySelectorAll(".profile").forEach(b=>b.onclick=()=>{profile=b.dataset.profile;localStorage.setItem("profile",profile);render()});init();
